### ISSUE TITLE
[Bug] Failed building wheel of lxml on python12 & python11

### ISSUE THREAD

**Issue by AyushSehrawat** [dreulavelle/iceberg#1]
`pip install -r requirements.txt` fails on Ubuntu on python11 & python12. Works fine on python10. 

![image](https://github.com/dreulavelle/Iceburg/assets/69469790/17212bec-028b-403b-a382-d2880ff987a9)

On further investigation, it is related to the version of `lxml`, removing it fixed the issue but raised another issue 

```
[2023-12-08 14:48:15 | DEBUG] <settings.load> - Settings loaded from settings.json
Traceback (most recent call last):
  File "/home/mini/projects/iceburg/src/main.py", line 10, in <module>
    from utils.ui_helpers import CustomJSONEncoder
  File "/home/mini/projects/iceburg/src/utils/ui_helpers.py", line 3, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/home/mini/.pyenv/versions/3.12.0/lib/python3.12/site-packages/flask/json/__init__.py)
```

Seems like newer version of flask.json doesn't have JSONEncoder.

**Comment by dreulavelle** [comment]
Yes, I already know about this lol :)

**Comment by AyushSehrawat** [comment]
@dreulavelle update or swith to fastapi ig 🙄

**Comment by AyushSehrawat** [comment]
Solved with moving to fastapi and removing version requirements from requirements.txt
