### ISSUE TITLE
Feature Request: Check for Missing Episodes in Plex

### ISSUE THREAD

**Issue by drondeseries** [dreulavelle/iceberg#10]
<details>
  <summary><strong>Feature Request: Check for Missing Episodes in Plex</strong></summary>

  <strong>Description:</strong><br>
  I propose enhancing Iceburg to check for missing episodes within Plex, providing users with an efficient way to manage their library.

  <strong>Details:</strong><br>
  - <strong>Functionality:</strong> Iceburg could scan a user's Plex library to identify missing episodes.<br>
  - <strong>Action on Missing Episodes:</strong> Options to automatically add missing episodes or log them in a file.<br>
  - <strong>User Configuration:</strong> Allow customization such as directories to search or handling preferences.<br>
  - <strong>Notification:</strong> Notify users about missing episodes and actions taken.

  <strong>Benefits:</strong><br>
  - <strong>Enhanced User Experience:</strong> Simplifies managing missing episodes within Plex.<br>
  - <strong>Efficiency:</strong> Saves time for users maintaining a complete library.<br>
  - <strong>Flexibility:</strong> Customizable options suit different user preferences.

  <strong>Request:</strong><br>
  I request the Iceburg team to consider implementing this feature, benefiting Plex users and enhancing Iceburg's utility.

  Thank you for your consideration.

  Best regards,<br>
  KAKA
</details>

**Comment by dreulavelle** [comment]
I like the idea of always having all the episodes for a given show and making sure that all episodes actually exist.

**Comment by dreulavelle** [comment]
@Gaisberg Should try and squeeze this in if possible? Or think about how we should handle episodes that are missing from Plex (unreleased episodes).

To branch off of this idea as well, could look into adding a feature to get missing movies that are part of a collection. For example if you have Iron man 1 and 3, then it would grab Iron Man 2. This feature could be toggleable as well of course.

**Comment by Gaisberg** [comment]
This is already implemented apart from configuring it. All missing episodes will be searched for after they are aired.

**Comment by dreulavelle** [comment]
I'll mark completed then. Can revisit the Collection feature later. I wonder if we can work/integrate with PMM at all.
