### ISSUE TITLE
[Web Improvement] Switch to local from google fonts for faster load times and privacy

### ISSUE THREAD

**Issue by AyushSehrawat** [dreulavelle/iceberg#102]

**Comment by KingPin** [comment]
- Would Google fonts not be faster due to caching on visitors' comps from other sites _possibly_ using the same fonts (especially using popular ones like Roboto)
- leverages Google CDN for delivery of files so speed technically should be faster unless loading over LAN.

however, privacy concerns are def on point. no reason to send IP/UA to an external service.

**Comment by AyushSehrawat** [comment]
> * Would Google fonts not be faster due to caching on visitors' comps from other sites _possibly_ using the same fonts (especially using popular ones like Roboto)
> * leverages Google CDN for delivery of files so speed technically should be faster unless loading over LAN.
> 
> however, privacy concerns are def on point. no reason to send IP/UA to an external service.

- CSS for fonts are only cached for about a day after which the expiration header kicks in and the font we are using isn't really common too. So i thought, how bout we just bundle it with the app only + the privacy there too 😄

**Comment by AyushSehrawat** [comment]
Also seems like cross site caching is no more done

https://wicki.io/posts/2020-11-goodbye-google-fonts/

**Comment by KingPin** [comment]
> * CSS for fonts are only cached for about a day after which the expiration header kicks in and the font we are using isn't really common too. So i thought, how bout we just bundle it with the app only + the privacy there too 😄

the cache part is now dead either way due to cache partitioning in Chrome/FF so it doesn't apply anymore. so even more reason to pack the files in with the app.

**Comment by AyushSehrawat** [comment]
> > * CSS for fonts are only cached for about a day after which the expiration header kicks in and the font we are using isn't really common too. So i thought, how bout we just bundle it with the app only + the privacy there too 😄
> 
> the cache part is now dead either way due to cache partitioning in Chrome/FF so it doesn't apply anymore. so even more reason to pack the files in with the app.

Yup, i will soon pack the files with the app build with something like https://fontsource.org/ (npm install)

**Comment by AyushSehrawat** [comment]
Implemented this in https://github.com/dreulavelle/iceberg/pull/109/commits/461360bb513513d3c1bf7306a54e78512d547c79 commit

Now the fonts are bundled with the application and there is no cumulative layout shift due to fonts which was earlier there (you see some other font and then other font on hard refresh or visiting after some time)
