### ISSUE TITLE
Feature Request: Integration of "Your Friends’ Watchlist" RSS Feed from Plex

### ISSUE THREAD

**Issue by drondeseries** [dreulavelle/iceberg#11]
<details>
  <summary><strong>Feature Request: Integration of "Your Friends’ Watchlist" RSS Feed from Plex</strong></summary>

  <strong>Description:</strong><br>
  I propose adding a feature to Iceburg that allows integration with "Your Friends’ Watchlist" RSS feed from Plex.

  <strong>Details:</strong><br>
  - <strong>Functionality:</strong> Enable Iceburg to access and interpret "Your Friends’ Watchlist" RSS feed from Plex.<br>
  - <strong>Use Case:</strong> Download Friend's watchlist .<br>

  <strong>Request:</strong><br>
  I kindly request the Iceburg development team to consider implementing the integration of "Your Friends’ Watchlist" RSS feed from Plex.

  Thank you for considering this feature addition.

  Best regards,<br>
  KAKA
</details>

**Comment by dreulavelle** [comment]
Worth mentioning that this is a Plex Pass only feature

**Comment by dreulavelle** [comment]
Implemented! 👍
