### ISSUE TITLE
Exception in plex.py

### ISSUE THREAD

**Issue by RajuDhl** [dreulavelle/iceberg#110]
I am getting the following exception.

```
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
Exception in thread Plex:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/iceberg/backend/program/plex.py", line 69, in run
    self._update_sections()
  File "/iceberg/backend/program/plex.py", line 161, in _update_sections
    if log_string:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'log_string' where it is not associated with a value
```

Removing the IF block does seem to fix the exception

```
if log_string:
    logger.debug("Updated section %s for %s", section.title, log_string)
```

**Comment by dreulavelle** [comment]
Ah I see why, that if statement is in the wrong indentation, or the `log_string = None` can be raised above where it's at. 

Don't worry about this though as we have a large update coming hopefully later today, or tomorrow.

**Comment by RajuDhl** [comment]
Same issue in new update.

**Comment by dreulavelle** [comment]
We've changed the settings so much, you need to make sure you have a new settings file. Also might be a good idea to get rid of your other pkl files as well.

Do a complete reset
