### ISSUE TITLE
App runs into infinite loop if content isn't found

### ISSUE THREAD

**Issue by RajuDhl** [dreulavelle/iceberg#127]
When the requested show isn't found by any scrappers, the app runs into an infinite loop.

For instance, while searching for [IMDB title tt3638644](https://www.imdb.com/title/tt3638644/). 

[log](https://pastebin.com/WdAWSdm4)

**Comment by RajuDhl** [comment]
It is no longer an issue in GH-82 branch..

tested and running fine since last few hrs

**Comment by dreulavelle** [comment]
@Gaisberg Should be good to merge now then. 2-3 people have tested at this point without any issues.
