### ISSUE TITLE
42 of the same tile of the show 

### ISSUE THREAD

**Issue by nammminn2** [dreulavelle/iceberg#140]
![CleanShot 2024-01-17 at 23 51 38@2x](https://github.com/dreulavelle/iceberg/assets/64177573/dad916e5-ede6-4ac7-b692-c0edc2c5a8ae)

**Comment by dreulavelle** [comment]
Apparently it's downloading the same item repeatably. And those are all downloading status.. 

This is in main branch

**Comment by dreulavelle** [comment]
It's possible this is a Zurg repair bug as well.

**Comment by Gaisberg** [comment]
Definately not us.
