### ISSUE TITLE
Wrong library is updated 

### ISSUE THREAD

**Issue by activ** [dreulavelle/iceberg#141]
Looks like it is trying to use the first movie or tv library it finds rather than the one that has the right path

```
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Fear the Invisible Man
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Secrets in the Marriage
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for He Went That Way
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Attack of the 50 Foot Camgirl
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Queen: Rock Montreal & Live Aid
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Girl in the Video
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for True Justice: Family Ties
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Destroy All Neighbors
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Roadkill
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for Lion of Judah Legacy
Iceberg  | [2024-01-18 05:41:39 | DEBUG] <symlink._symlink> - Created symlink for The Painter
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Fear the Invisible Man
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Queen: Rock Montreal & Live Aid
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for He Went That Way
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Roadkill
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Secrets in the Marriage
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for The Painter
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for True Justice: Family Ties
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Girl in the Video
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Destroy All Neighbors
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Attack of the 50 Foot Camgirl
Iceberg  | [2024-01-18 05:41:42 | DEBUG] <plex.update_item_section> - Updated section Concerts for Lion of Judah Legacy
```

![image](https://github.com/dreulavelle/iceberg/assets/1024884/9d3d804f-88dd-48e0-9aa5-c2c51d2959ea)
![image](https://github.com/dreulavelle/iceberg/assets/1024884/6c474f78-80dd-4a7e-93fd-c3c72c622313)
![image](https://github.com/dreulavelle/iceberg/assets/1024884/1d21838f-48c4-4db6-8ccc-0367859c2f6c)

**Comment by activ** [comment]
Yes, just checked my logs and it was still happening yesterday no the dev container.

**Comment by dreulavelle** [comment]
Can you explain your library dirs a little bit. It can help in recreating the issue on our end.

**Comment by activ** [comment]
Sure what do you want to know?
The iceberg  symlink library is in /mnt/library
The Rclone is in /mnt/iceberg

The library called Concerts is in /data/media/concerts 
then there is another movie library in /data/media/movies
and /mnt/zurg is relone to the zurg root 

Concerts and iceberg you can see in the screenshots above. Concerts is of the type movies library and it was probably the first library I created in this Plex instance. The iceberg libraries were created after all the other ones were already there.

The /data in docker is /srv/mergerfs/Data on my host os, /mnt/iceberg is the exact same on my host os.

For me it looks like iceberg chooses the movie library with the lowest id it finds rather than the one with the correct path. 
Let me know what more you need.

**Comment by dreulavelle** [comment]
> For me it looks like iceberg chooses the movie library with the lowest id it finds rather than the one with the correct path.
Let me know what more you need.

Ah it's possible we are selecting the first one we come across 🤔 

I can look into this later today after work. Ideally we should use the path of the symlink to determine what the Library dir/name its in.

**Comment by activ** [comment]
Just want to remark that this is still happening in the latest bug fix release.

**Comment by dreulavelle** [comment]
This issue has finally been put to rest as its now currently working! :)
