### ISSUE TITLE
Fix `_is_released` for determining when item is released

### ISSUE THREAD

**Issue by dreulavelle** [dreulavelle/iceberg#149]
`<jackett._scrape_item> - Could not find streams for Wonka`

This movie isn't even out yet. Overseerr shows only theatrical release, but no digital or physical. 

Googling this movie..
Theatrical Release: December 15, 2023
Digital Release: January 30, 2024
Physical Release: March 12, 2024

imdb id is `tt6166392`

**Comment by Gaisberg** [comment]
scraper check:
`    def _is_released(self, item) -> bool:
        return item.aired_at is not None and item.aired_at < datetime.now()`

trakt aired_at:
`    if getattr(data, "first_aired", None) and (
        item_type == "show"
        or (item_type == "season" and data.aired_episodes == data.episode_count)
        or item_type == "episode"
    ):
        aired_at = data.first_aired
        formatted_aired_at = datetime.strptime(aired_at, "%Y-%m-%dT%H:%M:%S.%fZ")
    if getattr(data, "released", None):
        released_at = data.released
        formatted_aired_at = datetime.strptime(released_at, "%Y-%m-%d")`

**Comment by dreulavelle** [comment]
fixed
