### ISSUE TITLE
Support Running without Mount & Plex

### ISSUE THREAD

**Issue by maxexcloo** [dreulavelle/iceberg#164]
I'd like to use this in a similar way to plex_debrid - basically as a media grabber for Infuse. I'll use zurg to connect Infuse to Real-Debrid.

Just opening discussion on this, was going to create my own but if we can share work that wouldn't be a bad thing - not sure it's possible without rewriting some base assumptions...

**Comment by dreulavelle** [comment]
Since we know exactly what the items are, there isn't a reason to not handle symlinking as well, so for that, it's required by the app.

**Comment by dreulavelle** [comment]
You can always setup plex and the mount, but not use them.

**Comment by maxexcloo** [comment]
Mounting might be okay but do we need Plex? What exactly is it used for (library? I use Trakt for that atm)

**Comment by dreulavelle** [comment]
Plex is how you watch the downloaded content you get from requesting stuff. Similar to plex_debrid basically. How do you watch your content now?

**Comment by maxexcloo** [comment]
Infuse - I find it simpler as it negates the need for anything but Zurg and I'm only hosting for myself anyway. Although in future I may try using it again.

**Comment by dreulavelle** [comment]
ah Mac/iOS/Infuse user. Fair enough man. The app may not be for you possibly, may continue to use Infuse and/or looking into Stremio (if its supported on that?)
