### ISSUE TITLE
Requests are stuck in "Requested" state

### ISSUE THREAD

**Issue by puppinoo** [dreulavelle/iceberg#178]
Hi,
Complete newbie here so sorry if I'll waste your time.

I installed iceberg on my VPS with Plex and RClone.
Configured everything putting my RCLone path in Host Path and Container Path (I have no Plex container. I installed natively). I installed rclone with zurg so I put the mounted path /mnt/zurg (also tried wih mount name "zurg" and even with WebDav RD path: dav.r***-d****d.com url.

Iceberg interface on port 3000 find the requests but they dont seem to reach RD cause they stay in Requested state.
I also installed Overseerr even though I'd like to keep it simple using RClone / Plex stack and put my api key. It seems to see plex and requests but no change from there. Always in requested.

Wht am I doing wrong? 

Thanks and again sorry to bother.

**Comment by dreulavelle** [comment]
Currently we are having issues that we are trying to sort out as well as improve overall performance. Please check us out on Discord to follow updates! :)
