### ISSUE TITLE
[Feature] Watchlist RSS feed in settings needs to be set to REDACTED

### ISSUE THREAD

**Issue by dreulavelle** [dreulavelle/iceberg#18]
This field shows up in logs. Needs to be hidden as its a public url.

**Comment by AyushSehrawat** [comment]
@dreulavelle do in UI too ?

**Comment by dreulavelle** [comment]
Yeah

**Comment by AyushSehrawat** [comment]
Watchlist RSS feed is now blurred in frontend, but we need to rename plex_watchlist.watchlist to plex_watchlist.rss

```
{
    plex_watchlist: {
        rss: 'here'
...
```

**Comment by dreulavelle** [comment]
Closing. Duplicate issue. Also, plex watchlist is going to get redone when I can get to it.
