### ISSUE TITLE
[BUG] Don't make core services true if one of the sub services fail

### ISSUE THREAD

**Issue by AyushSehrawat** [dreulavelle/iceberg#203]
If user has 2 content services enabled and one of them fails to validate/run, then the core content service is still true. I believe this issues needs to be fixed from the backend instead of frontend.

**BUT** , if one of the core services fail then https://github.com/dreulavelle/iceberg/issues/168 (the onboarding) will happen so we need to discuss how we can differentiate between them

**Comment by Gaisberg** [comment]
core content service should fail if one fails, minimum requirement for it is that we have 1 service up and running.

**Comment by AyushSehrawat** [comment]
> core content service should fail if one fails, minimum requirement for it is that we have 1 service up and running.

Currently if out of 2 services 1 fails, it's still true, hope you make it false so either user disable the wrong service or fix it. Allowing wrong config will just give more errors

**Comment by AyushSehrawat** [comment]
edit: fix is front-end manually checks

To be implemented~
