### ISSUE TITLE
Filter syntax

### ISSUE THREAD

**Issue by rendez2k** [dreulavelle/iceberg#214]
Hello there, not a bug, but if I wanted high-quality releases, only in English, how would I modify the default sort=sizequality%7Cqualityfilter=480p,scr,cam ? Would I need to exude every language?

**Comment by rendez2k** [comment]
Thanks! Guess no way to exclude none-english though?

**Comment by dreulavelle** [comment]
Currently languages haven't been implemented as it's gonna have to be redone.

This will be a big update coming, but I've been working on other bugs. So I haven't gotten to start it yet.

**Comment by dreulavelle** [comment]
One thing you can do in the meantime is limit the type of non-english sources your using.. so get rid of like half of the sources on torrentio :P

**Comment by rendez2k** [comment]
So this basically? Should the %7C go inbetween providers and quality?

sort=sizequality%7Cproviders=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl|qualityfilter=brremux,hdrall,dolbyvision,4k,720p,480p,other,scr,cam,unknown

**Comment by rendez2k** [comment]
So this at a guess:

sort=sizequality%7Cproviders=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetd%7Cqualityfilter=brremux,hdrall,dolbyvision,4k,720p,480p,other,scr,cam,unknown

**Comment by dreulavelle** [comment]
you dont have to do the %7C, it'll get encoded on our end.. so you dont have to worry.. you can just extract the filters out of the url, and paste it in Iceberg

**Comment by dreulavelle** [comment]
Ah I did notice one thing on your filter, you should drop the `unknown` at the end. These are safe. Torrents that torrentio cant get a quality from, it puts it into a "unknown" category.. but we care about resolution currently, so unknown torrents from Torrentio are still good torrents. 

The only scenario where you would want to include that, would be if you cared about 4K or high quality content..

**Comment by rendez2k** [comment]
Got it!
