### ISSUE TITLE
Wrong file selected and wrong symlinks

### ISSUE THREAD

**Issue by aamorin** [dreulavelle/iceberg#217]
### Description
Using Overseerr, I've added a series of movies that belong to a collection (but I added them one by one, not the collection). 
For each one of these movies, Iceberg selected the same Collection torrent, all of which with the same two files selected , instead of selecting the one it was actually looking for (which was in fact inside of the collection file).

Then, it created symlinks for each movie I requested, but all pointing to the same file (just one of the two selected ones).

I'm running the latest `dev` tag.

**Comment by dreulavelle** [comment]
Logs and/or images would be appreciated! Thank you. I'll get on this asap!

**Comment by aamorin** [comment]
![Screenshot 2024-02-09 at 12 09 34](https://github.com/dreulavelle/iceberg/assets/5832671/23f593d1-e7c0-4884-a6ac-3cb5c4b46d57)
![Screenshot 2024-02-09 at 12 09 43](https://github.com/dreulavelle/iceberg/assets/5832671/0d5dfa62-ae2d-43a0-ad05-6a06eb4acf16)
![Screenshot 2024-02-09 at 12 13 17](https://github.com/dreulavelle/iceberg/assets/5832671/472081bb-1b14-4198-a192-3c9eb41de6b8)
![Screenshot 2024-02-09 at 15 44 33](https://github.com/dreulavelle/iceberg/assets/5832671/e23672c5-1135-46cb-b1f8-5605c4e451b7)
_A friend_ sent me these :D

**Comment by aamorin** [comment]
Pictures removed due to the sensitivity of the content; they have been shared by other means of communication. Feel free to ping me if you need further info.

**Comment by dreulavelle** [comment]
Will be in the next patch
