### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by skearney414** [dreulavelle/iceberg#240]
Hello, I have set this up on docker from scratch. 

Coupe of issues that need fixing :) 

1. coverage and deepdiff not included in requirements.txt 
2. The file  [symlink.py](https://github.com/dreulavelle/iceberg/blob/main/backend/program/libaries/symlink.py) needs to be updated to check that the shows, seasons dir exists. it will not exist on first launch and will crash out 

i made this code change to get it working 

`import os
import re
from pathlib import Path

from utils.logger import logger
from program.settings.manager import settings_manager
from program.media.item import (
    MediaItem,
    Movie,
    Show,
    Season,
    Episode,
    ItemId
)

class SymlinkLibrary:
    def __init__(self):
        self.key = "symlinklibrary"
        self.last_fetch_times = {}
        self.settings = settings_manager.settings.symlink
        self.initialized = True

    def run(self) -> MediaItem:
        """Create a library from the symlink paths.  Return stub items that should
        be fed into an Indexer to have the rest of the metadata filled in."""
        movies = [
            (root, files[0]) 
            for root, _, files 
            in os.walk(self.settings.library_path / "movies") 
            if files
        ]
        for path, filename in movies:
            imdb_id = re.search('(tt\d+)', filename)
            if not imdb_id:
                logger.error("Can't extract episode imdb_id at path %s", path / filename)
                continue
            movie_item = Movie({'imdb_id': imdb_id.group()})
            movie_item.update_folder = "updated"
            yield movie_item
        
        shows_dir = self.settings.library_path / "shows" 
        if shows_dir.exists() and shows_dir.is_dir():
            for show in os.listdir(shows_dir):
                imdb_id = re.search(r'(tt\d+)', show)
                title = re.search(r'(.+)?( \()', show)
                if not imdb_id or not title:
                    logger.error(
                        "Can't extract episode imdb_id or title at path %s", 
                        shows_dir / show
                    )
                    continue
                show_item = Show({'imdb_id': imdb_id.group(), 'title': title.group(1)})
                season_dir = shows_dir / show
                if season_dir.exists() and season_dir.is_dir():
                    for season in os.listdir(season_dir):
                        if not (season_number := re.search(r'(\d+)', season)):
                            logger.error(
                                "Can't extract episode number at path %s", 
                                season_dir / season
                            )
                            continue
                        season_item = Season({'number': int(season_number.group())})
                        episode_dir = season_dir / season
                        if episode_dir.exists() and episode_dir.is_dir():
                            for episode in os.listdir(episode_dir):
                                if not (episode_number := re.search(r's\d+e(\d+)', episode)):
                                    logger.error(
                                        "Can't extract episode number at path %s", 
                                        episode_dir / episode
                                    )
                                    continue
                                episode_item = Episode({'number': int(episode_number.group(1))})
                                episode_item.symlinked = True
                                episode_item.update_folder = "updated"
                                season_item.add_episode(episode_item)
                        else:
                            logger.error("Episode directory not found: %s", episode_dir)
                else:
                    logger.error("Season directory not found: %s", season_dir)
                yield show_item
        else:
            logger.error("Shows directory not found: %s", shows_dir)
`

**Comment by dreulavelle** [comment]
this is all in a new branch, just havent committed it yet :P 

Thank you though! :)

**Comment by skearney414** [comment]
Ah perfect thanks, if I am using zurg, what should rclone path be?  Given
my zurg mount is /home/sean/plex/pd_zurg/mnt and my library is
/home/sean/plex/pd_zurg/mnt/zurg?

**Comment by dreulavelle** [comment]
technically, Iceberg isn't ready at the moment, however if you would still like to test then the rclone path should be where your rclone mount is.

Library can be where ever you want, as long as Plex see's the path (as well as Iceberg)

**Comment by skearney414** [comment]
I’ll give it a test if I can, plex debrid keeping duplicating stuff for me
so would like to try. Ah can see in the logs iceberg doesn’t have
permission. Will try and get it up and running . Thanks

**Comment by dreulavelle** [comment]
`/mnt:/mnt` in the docker compose makes it stupid easy to get going.. just have rclone put the zurg mount on like.. `/mnt/zurg` and then create a dir on `/mnt/library` for your library.. make sure these have the proper user permissions as well for Iceberg and Plex as well as Rclone to all be able to access...

That's how I have mine setup. Then its just,

Rclone Path: `/mnt/zurg`
Library Path: `/mnt/library`

**Comment by skearney414** [comment]
Yeah that makes sense I got it all working but the setup screens are
returning errors when populating plex rss url or mdblists .. the section
for plex library’s fails too even though the logs say it was set up :)
