### ISSUE TITLE
Plex init issue

### ISSUE THREAD

**Issue by skearney414** [dreulavelle/iceberg#250]
Hi there, 
Seems to be an issue when initializing plex as part of onboarding 

Plex service(s) failed to initialize. Please check your settings.

However, no issues in logs etc - maybe due to internal ip ? using 192.168.1.110:32400

**Comment by dreulavelle** [comment]
Currently now isn't a good time to test, as the app is undergoing large changes. 

We will let the community know when it's ready for testing, thanks!
