### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by skearney414** [dreulavelle/iceberg#282]
Just wanted to say this is impressive. So quick to download and symlink wow. 

Just one issue that you might not be aware of. The mediaServerSettingsServices const in helpers.ts within the lib/forma should be plexlibrary. If it's not plex settings won't save. Same goes for content. When you save plex watchlists it checks content which does not exist on the services end point.

**Comment by skearney414** [comment]
Also, in scrapers, __init__.py if there is not a result for a full season it will fall over :) 
Adding except StopIteration and break under line 31 resolves all issues

**Comment by dreulavelle** [comment]
Ah, appreciate it! Feel free to submit a PR and we will go over it. We are looking for additional dev's for the project as a couple of our dev's have been away for work or personal reasons.

**Comment by skearney414** [comment]
I'm happy to help with any front end stuff. Day job is react/ts and dot net but happy to help with backend too if needed

**Comment by dreulavelle** [comment]
We had a large rewrite for the backend not too long ago that seems a bit unfinished. If you're able to, fork it and run the app and if you can correct anything, that'd be greatly appreciated. 

If you do submit a PR, be sure to be descriptive about it and what it aims to fix/correct. You can message me on Discord as well if you have additional questions.

I'm @Spoked on there. Much appreciated man! Look forward to seeing what you can do!

**Comment by AyushSehrawat** [comment]
> Just wanted to say this is impressive. So quick to download and symlink wow.
> 
> Just one issue that you might not be aware of. The mediaServerSettingsServices const in helpers.ts within the lib/forma should be plexlibrary. If it's not plex settings won't save. Same goes for content. When you save plex watchlists it checks content which does not exist on the services end point.

Frontend is yet to catch up with backend, hence the bugs 😅

**Comment by dreulavelle** [comment]
@skearney414 reach out to me on discord, we are getting closer now. Just finishing up getting the debrid module finished.
