### ISSUE TITLE
[feature] Ability to not use Plex at all

### ISSUE THREAD

**Issue by toneman77** [dreulavelle/iceberg#286]
Hi. Right now im using plex_debrid with trakt to just update RD, then use the zurg mount in emby to watch the content. So:
Add stuff to trakt watchlist (movie) and trakt list (shows) --> gets added to RD --> scraped by emby via a folder.

Right now I can't even finish the onboarding without Plex. 

Possibility to setup with just trakt lists + RD would be awesome.

**Comment by dreulavelle** [comment]
It's on the roadmap to set items to be completed after they are done being symlinked.

Also, the website hasn't been updated in forever. The app is still in development. For testing purposes, just let Iceberg create a settings file in the data dir.. then stop Iceberg and edit that file.. then start it up again. For now don't use the website.

We will also be adding support for Emby and Jellyfin, we are just prioritizing working out the kinks first for the rest of the app before adding those apps. Same goes with Trakt. Trakt support will come soon.

**Comment by dreulavelle** [comment]
Closing, as this stuff is already planned.
