### ISSUE TITLE
How can I make this work?

### ISSUE THREAD

**Issue by bartje885** [dreulavelle/iceberg#317]
from my understanding there are still a few issues with the frontend, so my question is, is this project usable and can I configure it another way?

**Comment by dreulavelle** [comment]
yes, but you'll have to use the bug_fixes branch currently, and just do `make run` ... then stop it, and configure the settings.json file in the `data` directory.. then `make run` again..

if you need to restart/reset your data (dont worry, settings wont be touched) then you can do `make clean` and then `make run` again.
