### ISSUE TITLE
[Feature Request] User Authentication

### ISSUE THREAD

**Issue by dreulavelle** [dreulavelle/iceberg#37]
Would be good to have a single user auth. I plan on adding this to my FQDN. 

I can manage it through Cloudflare ACL's or Authentik or something.. but would be cool for a simple login form

**Comment by AyushSehrawat** [comment]
Why would we need external services for auth? We can manage ourselves ig similar to overseer

**Comment by dreulavelle** [comment]
Thats why I added this feature req. ;)

**Comment by AyushSehrawat** [comment]
closed as it's same as https://github.com/dreulavelle/iceberg/issues/61
