### ISSUE TITLE
[Feature] Hide url in logs

### ISSUE THREAD

**Issue by activ** [dreulavelle/iceberg#87]
Hey, 

The api keys are already automatically hidden from logs, could we also do the same for the url? That will make is easier to provide logs when reporting issues.

activ

**Comment by dreulavelle** [comment]
If we hide URL's.. then should we just hide all settings at that point? lol @Gaisberg

**Comment by Gaisberg** [comment]
Hmm yeah, urls do help with finding issues with configurations. So maybe not, lets wait and see for more comments about this before acting.
